### ISSUE TITLE
Does not specify a license

### ISSUE THREAD

**Issue by madebyjeffrey** [Birdasaur/FXyz#6]
Nothing in the project seems to specify a license, which makes using the project difficult for some.

**Comment by cbutler-am** [comment]
May I recommend Lesser GPL in preference to ordinary GPL if that is possible and still meets your needs with respect to use within a potentially proprietary program? Interpretation of the license language for GPL is not very intuitive when it comes to libraries.

**Comment by chin-apse** [comment]
A personal preference so that commercial use is allowed... Apache.

**Comment by jdub1581** [comment]
Hey guys, thanks for being patient. 

We are currently in the middle of preparing for an official release,
and integrating our project into Maven Central.

We have adopted the GPL3 license, and all sources will be updated in the mentioned release.

We will let you know when the release is out.
~jdub1581

**Comment by jdub1581** [comment]
Hey fellas, We have just released a Sampler as well as integrated GPL3.
Found here: https://github.com/FXyz/FXyz
