### ISSUE TITLE
Constructive Solid Geometry 

### ISSUE THREAD

**Issue by AnirvanSarkar** [Birdasaur/FXyz#7]
I would be nice if FXyz provide a feature to create 3D Shapes using boolean operations like union, intersection, subtraction etc.

For example:
![Constructive Solid Geometry](http://upload.wikimedia.org/wikipedia/commons/8/8b/Csg_tree.png)

**Comment by jperedadnr** [comment]
As of now, we use JCSG as a dependency, and you can create a TexturedMesh from any given CSG primitive with CSGMesh, or you can export any JavaFX mesh to CSG using Mesh2CSG. Check the test CuboidCSGTest, where boolean operations are used for substracting a cube from a cuboiod, and addding a prism.
